/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DotLoading: typeof import('./src/components/UI/DotLoading.vue')['default']
    MyDataTable: typeof import('./src/components/MyDataTable.vue')['default']
    StatusController: typeof import('./src/components/StatusController.vue')['default']
  }
}
